name: build

on:
  workflow_call:
    inputs:
      go_version:
        type: string
        required: false
        default: 1.19

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    defaults:
      run:
        working-directory: ./go/src/github.com/${{ github.repository }}
    steps:
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ inputs.go_version }}
      - name: checkout ${{ github.repository }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ./go/src/github.com/${{ github.repository }}
      - name: build
        run: |
          make build
  golint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
  prettier:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0
    - name: Format code
      uses: iamnotaturtle/auto-gofmt@v1.0
      with:
        only_changed: True
